
// location.js
const nlp = require("compromise");

// Common Delhi areas/neighborhoods to match explicitly if NLP misses them
const delhiKnownPlaces = [
  "Aali",
  "Aashirwad Enclave",
  "Adarsh Nagar",
  "Adarsh Nagar Metro Station",
  "Adchini",
  "Ahinsa Sthal",
  //"AIIMS",
  //"AIIMS Metro Station",
  "Akbar Pur Majra",
  "Akshardham",
  "Akshardham Metro Station",
  "Alaknanda",
  "Alipur",
  "Ambedkar Nagar",
  "Amrit Kaur Puri",
  "Anand Lok",
  "Anand Niketan",
  "Anand Parbat",
  "Anand Vihar",
  "Anand Vihar Metro Station",
  "Andrews Ganj",
  "Ansari Nagar",
  "Arjan Garh",
  "Arjan Garh Metro Station",
  "Arjun Nagar",
  "Asalat Pur Khawad",
  "Ashok Nagar",
  "Ashok Park Main",
  "Ashok Park Main Metro Station",
  "Ashok Vihar",
  "Ashok Vihar Phase 1",
  "Ashok Vihar Phase 2",
  "Ashok Vihar Phase 3",
  "Ashok Vihar Phase 4",
  "Ashram",
  "Ashram Chowk",
  "Ashram Metro Station",
  "Asola",
  "Aya Nagar",
  "Azad Nagar",
  "Azadpur",
  "Azadpur Metro Station",
  "Babar Pur",
  "Badami Bagh",
  "Badampur Majra Burari",
  "Badar Pur Khadar",
  "Badarpur",
  "Badarpur Border Metro Station",
  "Badli",
  "Bahadur Shah Zafar Marg",
  "Bakhtawar Pur",
  "Bakkar Wala",
  "Balbir Nagar",
  "Bali Nagar",
  "Bankauli",
  "Bankner",
  "Bapa Nagar",
  "Baqar Garh",
  "Baqiabad",
  "Barakhamba Road",
  "Barakhamba Road Metro Station",
  "Barwala",
  "Basaidarapur",
  "Batla House",
  "Bawana",
  "Bawana Industrial Area",
  "Bazid Pur Thakran",
  "Begum Pur",
  "Ber Sarai",
  "Bhagwan Das Road",
  "Bhajanpura",
  "Bhalaswa",
  "Bhalaswa Metro Station",
  "Bharat Nagar",
  "Bhati",
  "Bhikaji Cama Place",
  "Bhikaji Cama Place Metro Station",
  "Bhogal",
  "Bhor Garh",
  "Bidhpur",
  "Bihari Pur",
  "Bijwasan",
  "Bindapur",
  "Bodh Pur Bija Pur",
  "Budh Vihar",
  "Budh Vihar Phase 1",
  "Budh Vihar Phase 2",
  "Budhan Pur",
  "Burari",
  "Burari Metro Station",
  "Central Secretariat",
  "Central Secretariat Metro Station",
  "Chanakyapuri",
  "Chandan Hola",
  "Chandni Chowk",
  "Chandni Chowk Metro Station",
  "Chand Pur",
  "Chatesar",
  "Chawri Bazar",
  "Chawri Bazar Metro Station",
  "Chhatarpur",
  "Chhatarpur Enclave",
  "Chhatarpur Metro Station",
  "Chhawala",
  "Chilla Saroda Bangar",
  "Chilla Saroda Khadar",
  "Chirag Delhi",
  "Chirag Delhi Metro Station",
  "Chittaranjan Park",
  "Chokhandi",
  "Civil Lines",
  "Civil Lines Metro Station",
  "Connaught Place",
  "Dabri",
  "Dabri Mor",
  "Dabri Mor Metro Station",
  "Dallo Pura",
  "Dariba Kalan",
  "Darya Ganj",
  "Darya Pur Kalan",
  "Darya Pur Khurd",
  "Dashrath Puri",
  "Dashrathpuri Metro Station",
  "Daulat Pur",
  "Dayal Pur",
  "Dayanand Colony",
  "Deenpur",
  "Deepali Chowk",
  "Defence Colony",
  "Deepali Chowk Metro Station",
  "Delhi Aerocity Metro Station",
  "Delhi Cantonment",
  "Delhi Cantonment Metro Station",
  "Delhi Gate",
  "Delhi Gate Metro Station",
  "Deorala",
  "Dera Mandi",
  "Derawal Nagar",
  "Dev Nagar",
  "Devli",
  "Dhansa",
  "Dhansa Bus Stand Metro Station",
  "Dhaula Kuan",
  "Dhaula Kuan Metro Station",
  "Dichaon Kalan",
  "Dilli Haat INA Metro Station",
  "Dilshad Colony",
  "Dilshad Garden",
  "Dilshad Garden Metro Station",
  "Dindar Pur",
  "Dr. Ambedkar Nagar",
  "Durgabai Deshmukh South Campus Metro Station",
  "Dwarka",
  "Dwarka Mor",
  "Dwarka Mor Metro Station",
  "Dwarka Sector 1",
  "Dwarka Sector 2",
  "Dwarka Sector 3",
  "Dwarka Sector 4",
  "Dwarka Sector 5",
  "Dwarka Sector 6",
  "Dwarka Sector 7",
  "Dwarka Sector 8",
  "Dwarka Sector 8 Metro Station",
  "Dwarka Sector 9",
  "Dwarka Sector 9 Metro Station",
  "Dwarka Sector 10",
  "Dwarka Sector 10 Metro Station",
  "Dwarka Sector 11",
  "Dwarka Sector 11 Metro Station",
  "Dwarka Sector 12",
  "Dwarka Sector 12 Metro Station",
  "Dwarka Sector 13",
  "Dwarka Sector 13 Metro Station",
  "Dwarka Sector 14",
  "Dwarka Sector 14 Metro Station",
  "Dwarka Sector 15",
  "Dwarka Sector 16",
  "Dwarka Sector 17",
  "Dwarka Sector 18",
  "Dwarka Sector 19",
  "Dwarka Sector 21",
  "Dwarka Sector 21 Metro Station",
  "Dwarka Sector 22",
  "Dwarka Sector 23",
  "Dwarka Sector 24",
  "Dwarka Sector 26",
  "Dwarka Sector 28",
  "Dyalpur",
  "East Azad Nagar",
  "East Azad Nagar Metro Station",
  "East Krishna Nagar",
  "East of Kailash",
  "East Vinod Nagar",
  "East Vinod Nagar Metro Station",
  "ESI Basaidarapur Metro Station",
  "Fateh Nagar",
  "Fateh Pur Jat",
  "Fatehpur Beri",
  "Freedom Fighter Enclave",
  "G T B Nagar",
  "G T B Nagar Metro Station",
  "Gadai Pura",
  "Gagan Vihar",
  "Gandhi Nagar",
  "Garhi Mandu",
  "Geetanjali Enclave",
  "Ghalib Pur",
  "Gharoli",
  "Gharonda Neemka Bangar",
  "Ghazipur",
  "Geeta Colony",
  "Gheora",
  "Ghevra Metro Station",
  "Ghitorni",
  "Ghitorni Metro Station",
  "Gokal Pur",
  "Gokulpuri Metro Station",
  "Goela Khurd",
  "Gole Market",
  "Golf Links",
  "Goman Hera",
  "Govindpuri",
  "Govindpuri Metro Station",
  "Greater Kailash",
  "Greater Kailash I",
  "Greater Kailash II",
  "Greater Kailash III",
  "Greater Kailash Metro Station",
  "Green Park",
  "Green Park Extension",
  "Green Park Metro Station",
  "GTB Enclave",
  "Gujranwala Town",
  "Gulabi Bagh",
  "Gulmohar Park",
  "Guru Tegh Bahadur Nagar",
  "Haiderpur",
  "Haiderpur Badli Mor Metro Station",
  "Hamid Pur",
  "Haqiqat Nagar",
  "Hareoli",
  "Hari Nagar",
  "Hari Nagar Ashram",
  "Harkesh Nagar",
  "Harkesh Nagar Okhla Metro Station",
  "Hasan Pur",
  "Hastsal",
  "Hauz Khas",
  "Hauz Khas Metro Station",
  "Hauz Khas Village",
  "Hiranki",
  "Holambi Kalan",
  "Holambi Khurd",
  "Humayunpur",
  "Ibrahim Pur",
  "IGI Airport",
  "IGI Airport Terminal 1 Metro Station",
  "IIT Delhi Metro Station",
  "INA",
  "INA Colony",
  "Inder Enclave",
  "Inderlok",
  "Inderlok Metro Station",
  "Inderpuri",
  "Indraprastha Extension",
  "Indraprastha Metro Station",
  "IP Extension Metro Station",
  "Iradat Nagar",
  "Isa Pur",
  "ITO Metro Station",
  "Jaffrabad",
  "Jaffrabad Metro Station",
  "Jafar Pur Kalan",
  "Jagat Pur",
  "Jahangir Puri",
  "Jahangirpuri Metro Station",
  "Jain Pur",
  "Jaitpur",
  "Jama Masjid",
  "Jama Masjid Metro Station",
  "Jamia Nagar",
  "Janakpuri",
  "Janakpuri East Metro Station",
  "Janakpuri West Metro Station",
  "Jangpura",
  "Jangpura Metro Station",
  "Janpath",
  "Janpath Metro Station",
  "Jasola",
  "Jasola Apollo Metro Station",
  "Jasola Vihar Shaheen Bagh Metro Station",
  "Jat Khor",
  "Jhandewalan",
  "Jhandewalan Metro Station",
  "Jhangola",
  "Jharoda Kalan",
  "Jharoda Majra Burari",
  "Jhatikra",
  "Jhilmil",
  "Jhilmil Colony",
  "Jhilmil Metro Station",
  "Jhuljhuli",
  "Jiwan Pur",
  "Jirpur",
  "Johri Enclave Metro Station",
  "Johripur",
  "Jona Pur",
  "Jonti",
  "Jor Bagh",
  "Jor Bagh Metro Station",
  "Kailash Colony",
  "Kailash Colony Metro Station",
  "Kair",
  "Kakrola",
  "Kalindi Kunj",
  "Kalindi Kunj Metro Station",
  "Kalkaji",
  "Kalkaji Mandir Metro Station",
  "Kalyan Puri",
  "Kalyan Vihar",
  "Kamal Pur",
  "Kamla Nagar",
  "Kangan Heri",
  "Kanhaiya Nagar Metro Station",
  "Kanjhawala",
  "Kapashera",
  "Karala",
  "Karampura",
  "Karawal Nagar",
  "Karkardooma",
  "Karkarduma Court Metro Station",
  "Karkarduma Metro Station",
  "Karol Bagh",
  "Karol Bagh Metro Station",
  "Kashmere Gate",
  "Kashmere Gate Metro Station",
  "Kathputli Colony",
  "Katwaria Sarai",
  "Kavita Colony",
  "Keshavpuram",
  "Keshav Puram Metro Station",
  "Khajoori Khas",
  "Kham Pur",
  "Khan Market",
  "Khan Market Metro Station",
  "Khanpur",
  "Khanpur Dhani",
  "Khari Baoli",
  "Kharkhari Jatmal",
  "Kharkhari Nahar",
  "Kharkhari Rond",
  "Khera Dabar",
  "Khera Kalan",
  "Khera Khurd",
  "Khirki Extension",
  "Kiran Vihar",
  "Kirari Suleman Nagar",
  "Kirti Nagar",
  "Kirti Nagar Metro Station",
  "Kishangarh",
  "Kohat Enclave",
  "Kohat Enclave Metro Station",
  "Kondli",
  "Kotla Mahigiran",
  "Kotla Mubarakpur",
  "Krishna Nagar",
  "Krishna Nagar Metro Station",
  "Krishna Park Extension Metro Station",
  "Kureni",
  "Kusum Pur",
  "L Zone",
  "Lad Pur",
  "Lado Sarai",
  "Lajpat Nagar",
  "Lajpat Nagar 1",
  "Lajpat Nagar 2",
  "Lajpat Nagar 3",
  "Lajpat Nagar 4",
  "Lajpat Nagar Metro Station",
  "Lal Kuan",
  "Lal Qila Metro Station",
  "Lam Pur",
  "Lawrence Road",
  "Laxmi Nagar",
  "Laxmi Nagar Metro Station",
  "Laxmibai Nagar",
  "Libas Pur",
  "Lodhi Colony",
  "Lok Kalyan Marg Metro Station",
  "Loknayakpuram",
  "Lutyens Delhi",
  "Madanpur Dabas",
  "Madanpur Khadar",
  "Madangir",
  "Madhu Vihar",
  "Maharani Bagh",
  "Mahipalpur",
  "Mahavir Enclave",
  "Maidan Garhi",
  "Majlis Park Metro Station",
  "Majnu ka Tilla",
  "Malik Pur Kohi",
  "Malik Pur Zer-Najafgarh",
  "Malviya Nagar",
  "Malviya Nagar Metro Station",
  "Mamoor Pur",
  "Mandawali",
  "Mandawali West Vinod Nagar Metro Station",
  "Mandi Hills",
  "Mandi House",
  "Mandi House Metro Station",
  "Manglapuri",
  "Mangolpur Kalan",
  "Mangolpuri",
  "Mangolpuri Metro Station",
  "Mansarover Garden",
  "Mansarovar Park",
  "Mansarovar Park Metro Station",
  "Matiala",
  "Maujpur",
  "Maujpur Babarpur Metro Station",
  "Mayapuri",
  "Mayapuri Metro Station",
  "Mayur Vihar",
  "Mayur Vihar Extension",
  "Mayur Vihar Extension Metro Station",
  "Mayur Vihar Phase 1",
  "Mayur Vihar Phase 1 Metro Station",
  "Mayur Vihar Phase 2",
  "Mayur Vihar Phase 3",
  "Meera Bagh",
  "Mehrauli",
  "Mithapur",
  "Mithe Pur",
  "Mitraon",
  "Model Town",
  "Model Town Metro Station",
  "Mohan Estate",
  "Mohan Estate Metro Station",
  "Mohan Garden",
  "Molar Band",
  "Moradabad Pahari",
  "Moti Bagh",
  "Moti Nagar",
  "Moti Nagar Metro Station",
  "Mubarak Pur Dabas",
  "Mukand Pur",
  "Mukherjee Nagar",
  "Mukhmel Pur",
  "Mundhela Kalan",
  "Mundhela Khurd",
  "Mundka",
  "Mundka Metro Station",
  "Mungesh Pur",
  "Munirka",
  "Munirka Metro Station",
  "Mustafabad",
  "Nabi Karim Metro Station",
  "Najafgarh",
  "Najafgarh Metro Station",
  "Nanak Heri",
  "Nand Nagri",
  "Nangal Raya",
  "Nangal Thakran",
  "Nangli Metro Station",
  "Nangli Poona",
  "Nangli Sakrawati",
  "Nangloi",
  "Nangloi Jat",
  "Nangloi Metro Station",
  "Naraina",
  "Naraina Vihar Metro Station",
  "Narela",
  "Naveen Shahdara",
  "Nawada",
  "Nawada Metro Station",
  "Neb Sarai",
  "Nehru Enclave Metro Station",
  "Nehru Place",
  "Nehru Place Metro Station",
  "Netaji Nagar",
  "Netaji Subhash Place",
  "Netaji Subhash Place Metro Station",
  "New Ashok Nagar",
  "New Ashok Nagar Metro Station",
  "New Delhi Metro Station",
  "New Friends Colony",
  "New Moti Bagh",
  "Nilothi",
  "Nirman Vihar",
  "Nirman Vihar Metro Station",
  "Nithari",
  "Nizamuddin",
  "Nizamuddin East",
  "Nizamuddin West",
  "Ochandi",
  "Okhla",
  "Okhla Bird Sanctuary Metro Station",
  "Okhla Phase 1",
  "Okhla Phase 2",
  "Okhla Phase 3",
  "Okhla Vihar",
  "Okhla Vihar Metro Station",
  "Old Delhi Railway Station",
  "Pahar Ganj",
  "Palam",
  "Palam Metro Station",
  "Palla",
  "Pamposh Enclave",
  "Panchsheel Enclave",
  "Panchsheel Park",
  "Panchsheel Park Metro Station",
  "Pandav Nagar",
  "Pansali",
  "Paprawat",
  "Paschim Vihar",
  "Paschim Vihar East Metro Station",
  "Paschim Vihar West Metro Station",
  "Patel Chowk",
  "Patel Chowk Metro Station",
  "Patel Nagar",
  "Patel Nagar Metro Station",
  "Patparganj",
  "Patparganj Industrial Area",
  "Peera Garhi",
  "Peeragarhi Metro Station",
  "Pehlad Pur Bangar",
  "Pindwala Kalan",
  "Pindwala Khurd",
  "Pitampura",
  "Pitampura Metro Station",
  "Pooth Kalan",
  "Pooth Khurd",
  "Pragati Maidan",
  "Pratap Nagar",
  "Pratap Nagar Metro Station",
  "Preet Vihar",
  "Preet Vihar Metro Station",
  "Prem Nagar",
  "Pul Pehlad",
  "Pul Pehladpur",
  "Pulbangash Metro Station",
  "Punjabi Bagh",
  "Punjabi Bagh East",
  "Punjabi Bagh West",
  "Punjabi Bagh West Metro Station",
  "Punjab Khor",
  "Pushp Vihar",
  "Pushpanjali Metro Station",
  "Qadi Pur",
  "Qazi Pur",
  "Qullak Pur",
  "Qutab Garh",
  "Qutub Minar",
  "Qutub Minar Metro Station",
  "Qutub Vihar",
  "R K Ashram Marg",
  "R K Ashram Marg Metro Station",
  "R K Puram",
  "R K Puram Metro Station",
  "Raghu Pur",
  "Raiasina Hill",
  "Raja Garden",
  "Raja Pur Kalan",
  "Rajdhani Park Metro Station",
  "Rajender Nagar",
  "Rajendra Place Metro Station",
  "Rajiv Chowk",
  "Rajiv Chowk Metro Station",
  "Raj Nagar",
  "Rajokri",
  "Rajouri Garden",
  "Rajouri Garden Metro Station",
  "Ramesh Nagar Metro Station",
  "Rampura",
  "Ranaji Enclave",
  "Rani Bagh",
  "Rani Khera",
  "Ranjeet Nagar",
  "Rangpuri",
  "Rasool Pur",
  "Razapur Khurd",
  "Rewla Kham Pur",
  "Rithala",
  "Rithala Metro Station",
  "Rohini",
  "Rohini East Metro Station",
  "Rohini Sector 1",
  "Rohini Sector 2",
  "Rohini Sector 3",
  "Rohini Sector 4",
  "Rohini Sector 5",
  "Rohini Sector 6",
  "Rohini Sector 7",
  "Rohini Sector 8",
  "Rohini Sector 9",
  "Rohini Sector 11",
  "Rohini Sector 13",
  "Rohini Sector 14",
  "Rohini Sector 15",
  "Rohini Sector 16",
  "Rohini Sector 17",
  "Rohini Sector 18",
  "Rohini Sector 18, 19 Metro Station",
  "Rohini Sector 19",
  "Rohini Sector 20",
  "Rohini Sector 21",
  "Rohini Sector 22",
  "Rohini Sector 23",
  "Rohini Sector 24",
  "Rohini Sector 25",
  "Rohini Sector 27",
  "Rohini Sector 28",
  "Rohini Sector 29",
  "Rohini Sector 30",
  "Rohini Sector 34",
  "Rohini Sector 35",
  "Rohini Sector 36",
  "Rohini West Metro Station",
  "Roop Nagar",
  "Roshan Pura",
  "Saba Pur Delhi",
  "Saba Pur Shahdara",
  "Sadat Pur Gujran",
  "Sadat Pur Musalmanan",
  "Sadar Bazaar Cantonment Metro Station",
  "Sadar Bazaar Metro Station",
  "Safdarjung Development Area",
  "Safdarjung Enclave",
  "Sagar Pur",
  "Sagarpur Metro Station",
  "Sahibabad Daulat Pur",
  "Saidabad",
  "Saidul Azaib",
  "Sainik Farm",
  "Saket",
  "Saket G Block Metro Station",
  "Saket Metro Station",
  "Salah Pur",
  "Salah Pur Majra",
  "Samas Pur Khalsa",
  "Samaypur Badli Metro Station",
  "Sambhalka",
  "Sangam Vihar",
  "Sanoth",
  "Sant Nagar",
  "Saoda",
  "Sarang Pur",
  "Sarai Kale Khan Metro Station",
  "Sarai Rohilla",
  "Sarai Rohilla Metro Station",
  "Sarita Vihar",
  "Sarita Vihar Metro Station",
  "Sarojini Nagar",
  "Sarojini Nagar Metro Station",
  "Sarvodaya Enclave",
  "Satbari",
  "Satguru Ram Singh Marg Metro Station",
  "Savitri Nagar",
  "Seelampur",
  "Seelampur Metro Station",
  "Seemapuri",
  "Shadipur",
  "Shadipur Metro Station",
  "Shahdara",
  "Shahdara Metro Station",
  "Shaheen Bagh",
  "Shahpur Garhi",
  "Shahpura",
  "Shakar Pur",
  "Shakti Nagar",
  "Shakurbasti",
  "Shakurpur Metro Station",
  "Shalimar Bagh",
  "Shalimar Bagh Metro Station",
  "Shamas Pur",
  "Shankar Vihar Metro Station",
  "Shanti Niketan",
  "Shastri Nagar",
  "Shastri Nagar Metro Station",
  "Shastri Park",
  "Shastri Park Metro Station",
  "Sheikh Sarai",
  "Sheikh Sarai Phase 1",
  "Sheikh Sarai Phase 2",
  "Sher Pur",
  "Sher Pur Deri",
  "Shikar Pur",
  "Shiv Enclave",
  "Shiv Ram Park",
  "Shiv Vihar Metro Station",
  "Shivaji Park Metro Station",
  "Shivaji Place",
  "Shivaji Stadium",
  "Shivaji Stadium Metro Station",
  "Sidhartha Nagar",
  "Sikanderpur",
  "Singhu",
  "Singhola",
  "Siras Pur",
  "Siri Fort",
  "Sonia Vihar",
  "South Extension",
  "South Extension Metro Station",
  "South Extension Part 1",
  "South Extension Part 2",
  "South Patel Nagar",
  "Sir M. Vishweshwaraiah Moti Bagh Metro Station",
  "Sri Niwaspuri",
  "Sriniwaspuri",
  "Subhash Nagar",
  "Subhash Nagar Metro Station",
  "Sukhdev Vihar",
  "Sukhdev Vihar Metro Station",
  "Sultan Pur",
  "Sultan Pur Dabas",
  "Sultan Pur Majra",
  "Sultanpur Metro Station",
  "Sunder Nagar",
  "Sunger Pur Delhi",
  "Supreme Court Metro Station",
  "Surakh Pur",
  "Surera",
  "Tagore Garden",
  "Tagore Garden Metro Station",
  "Taj Pur Kalan",
  "Taj Pur Khurd",
  "Taj Pul",
  "Tihar Village",
  "Tikri Kalan",
  "Tikri Kalan Metro Station",
  "Tilak Nagar",
  "Tilak Nagar Metro Station",
  "Timarpur",
  "Tis Hazari",
  "Tis Hazari Metro Station",
  "Tigi Pur",
  "Tigri",
  "Tikri Khurd",
  "Tri Nagar",
  "Trilokpuri",
  "Trilokpuri Sanjay Lake Metro Station",
  "Tughlakabad",
  "Tughlakabad Metro Station",
  "Tukhmir Pur",
  "Ujwa",
  "Urdu Bazaar",
  "Uttam Nagar",
  "Uttam Nagar East",
  "Uttam Nagar East Metro Station",
  "Uttam Nagar West",
  "Uttam Nagar West Metro Station",
  "Vasant Kunj",
  "Vasant Kunj Metro Station",
  "Vasant Vihar",
  "Vasant Vihar Metro Station",
  "Vasundhara Enclave",
  "Vikas Nagar",
  "Vikas Puri",
  "Vikaspuri",
  "Vidhan Sabha Metro Station",
  "Vijay Nagar",
  "Vijay Vihar",
  "Vigyan Vihar",
  "Vinobapuri Metro Station",
  "Vinod Nagar East",
  "Vinod Nagar West",
  "Vishal Enclave",
  "Vishwa Vidyalaya",
  "Vishwavidyalaya Metro Station",
  "Vishnu Garden",
  "Vishwas Nagar",
  "Vivek Vihar",
  "Wazirabad",
  "Wazirpur",
  "Welcome",
  "Welcome Metro Station",
  "West Enclave",
  "West Enclave Metro Station",
  "West Patel Nagar",
  "Yamuna Bank Metro Station",
  "Yamuna Pushta",
  "Yamuna Vihar",
  "Yamuna Vihar Metro Station",
  "Yashobhoomi Dwarka Sector 25 Metro Station",
  "Yojana Vihar",
  "Yusuf Sarai",
  "Zind Pur",
  "Ziauddin Pur"
];

function extractLocation(bodyText, title = "") {
  const fullText = `${title}. ${bodyText}`;
  const lowerText = fullText.toLowerCase();

  // 1. First Check: Direct match against known Delhi localities
  for (const place of delhiKnownPlaces) {
    if (lowerText.includes(place)) {
      // Capitalize first letters neatly
      return place.replace(/\b\w/g, l => l.toUpperCase());
    }
  }

  // 2. Fallback: Use NLP Named Entity Recognition for Place names
  const doc = nlp(fullText);
  const places = doc.places().out("array");

  const filtered = places.filter(place => {
    const p = place.toLowerCase().trim();
    return p !== "delhi" && p !== "india" && p !== "police" && p !== "station" && p !== "court";
  });

  if (filtered.length > 0) {
    return filtered[0].replace(/\b\w/g, l => l.toUpperCase());
  }

  return "Unknown";
}

module.exports = extractLocation;